### ISSUE TITLE
error: piramide_fcovid

### ISSUE THREAD

**Issue by jincio** [jincio/covidPeru#9]
Revisar esto: 
Error: Insufficient values in manual scale. 3 needed but only 2 provided

**Comment by vzavaletag** [comment]
Buenas tardes solo con Lima me sale ese error, cambie Lima por Cajamarca y R
esta bien.

**Comment by vzavaletag** [comment]
Muchas gracias, muchas bendiciones

**Comment by jincio** [comment]
saludos, Claudia Escobar ya solucionó el bug. 
Cualquier cosa avisan.
